[package]
name = "mpu6050"
version = "0.1.0"
authors = ["Julian Gaal <gjulian@uos.de>"]
edition = "2018"

[dependencies]
i2cdev = "0.4.1"
embedded-hal = "0.2.2"
linux-embedded-hal = "0.2.2"
libm = "0.1.2"
