version: 2
jobs:
  latest:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: 
          name: build and test
          command: cargo build && cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - latest

