version: 2
jobs:
  latest:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - run: 
          name: build and test
          command: cargo build
  fournine:
    docker:
      - image: circleci/rust:1.49.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  foureight:
    docker:
      - image: circleci/rust:1.48.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  fourseven:
    docker:
      - image: circleci/rust:1.47.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  foursix:
    docker:
      - image: circleci/rust:1.46.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  fourfive:
    docker:
      - image: circleci/rust:1.45.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  fourfour:
    docker:
      - image: circleci/rust:1.44.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  fourthree:
    docker:
      - image: circleci/rust:1.43.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  fourtwo:
    docker:
      - image: circleci/rust:1.42.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  fourone:
    docker:
      - image: circleci/rust:1.40.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build
  fourzero:
    docker:
      - image: circleci/rust:1.40.0
    steps:
      - checkout
      - run:
          name: build and test
          command: cargo build

workflows:
  version: 2
  build_and_test:
    jobs:
      - latest
      - fournine
      - foureight
      - fourseven
      - foursix
      - fourfive
      - fourfour
      - fourthree
      - fourtwo
      - fourone
      - fourzero

